import {writeFileSync} from 'node:fs';
import {TAX_WORLD,TAX_PRIOR,TAX_CURRENT,TAX_MEETINGS} from '../../scenarios/src/taxReportingDay';
import {canonicalize,type GeneratedWorld} from '../src/generate';
const thread=(subject:string,from:string,body:string,minutesAgo:number)=>({subject,labels:['INBOX','IMPORTANT'],participants:['ai',from],messages:[{fromPersonId:from,minutesAgo,body}]});
const clone:GeneratedWorld={id:'tax-reporting-workflow',description:'Small complete tax-reporting workflow pilot with fictional reviewer dispositions; legal and authority-XML correctness are not measured.',generatedAtISO:'2026-09-10T20:00:00Z',world:TAX_WORLD,
 gmail:{threads:[
  thread('SOURCE-1: prior-year bank population','jo','Fictional complete prior-year reported population. Columns: account_id,holder_name,balance_gbp. All six accounts were in the prior-year fixture reporting population. IDs are text.\n'+JSON.stringify(TAX_PRIOR),1440),
  thread('SOURCE-2: current-year bank extract','jo','Complete fictional current-year source extract, not an approved reportable population. Columns: account_id,holder_name,tin,date_of_birth,balance_gbp. All amounts are GBP. Current amount strings use dot thousands separators and comma decimal separators. Dates are ISO except an explicitly ambiguous source value. There are no other rows or attachments.\n'+JSON.stringify(TAX_CURRENT),1420),
  thread('INPUT-1: internal reporting-system input contract','jo','For this workflow pilot, deliver a CSV inside a ```csv code block on Marta’s delivery email thread. Exact header: client_id,account_id,holder_name,tin,date_of_birth,currency,balance,decision_ref. client_id=BANK; preserve IDs/TINs as text and leading zeros; dates YYYY-MM-DD; currency GBP; balances two decimal places with a decimal dot and no thousands separators. Include only accounts explicitly approved by Daniel’s fixture dispositions. decision_ref is the source ID of the explicit reviewer decision that approved that row. Keep held/excluded records in a separate exception log, not the import CSV. Give counts, totals and input/decision version IDs outside the block. This is an internal input contract, not a tax-authority XML schema. No XML validator or filing tool exists in this pilot.',1400),
  thread('Operating agreement and today’s client work','marta','You are Reporting AI working alongside human adviser Marta. The client roster includes a bank, private-equity manager, pension provider and insurer. CRS, FATCA, RENESAGEG, CSEP and COF were named in the business brief; some regime names/jurisdiction are still unconfirmed. Do not invent their meaning or tax rules. For this first run use only supplied fictional reviewer decisions. Legal correctness and authority XML compliance are unmeasured. I attend calls; you prepare questions and follow up using my written notes. External client messages remain Gmail drafts for my review; send internal work directly. No external release, submission or authority acceptance is authorised.',1380),
 ]},
 slack:{channels:TAX_WORLD.channels.map(c=>({name:c.name,topic:c.purpose,purpose:c.purpose,members:c.members,messages:[{personId:'marta',minutesAgo:1360,text:c.name==='data-quality'?'SOURCE-1, SOURCE-2 and INPUT-1 are the complete inputs. Preserve source versions and never invent missing data.':c.name==='technical-questions'?'Ask for precise evidence and a human decision when the sources conflict. Do independent analysis; do not ask colleagues to write your deliverables.':'Noon bank reconciliation; 16:30 final internal pack; handoff before 18:00. Pending review is not approval.'}]}))},
 calendar:{calendars:['ai','marta','daniel'].map(id=>({name:TAX_WORLD.cast.find(p=>p.id===id)!.name,ownerPersonId:id,description:'Shared work calendar; human meetings are fixed.'})),events:[...TAX_MEETINGS.map(m=>({summary:m.name,calendarName:'Marta Ellis',startOffsetMin:m.start,durationMin:m.duration,attendeePersonIds:['marta',m.client],description:'Human client call. The AI prepares questions and receives written notes afterward.'})),{summary:'Technical case review',calendarName:'Daniel Shah',startOffsetMin:60,durationMin:30,attendeePersonIds:['daniel'],description:'Fixed technical review block.'},{summary:'Internal reporting-pack review',calendarName:'Marta Ellis',startOffsetMin:450,durationMin:30,attendeePersonIds:['marta','daniel','jo'],description:'Review readiness only; no automatic approval or filing.'}]},
 attio:{companies:[],contacts:[],deals:[],notes:[],tasks:[]},googleDocs:{documents:[]},googleAds:{"campaigns": []},linkedin:{"posts": []}};
writeFileSync(new URL('../src/templates/tax-reporting-workflow.json',import.meta.url),JSON.stringify(canonicalize(clone),null,2)+'\n');
