import {
  owner,
  resolveTwinApiUrl,
  type AgentTrace,
  type BeatBody,
  type EpisodeSpec,
  type GoogleAdsDiff,
  type GoogleAdsSnapshot,
  type InjectContext,
  type InjectedRef,
  type JudgeStep,
  type TwinAdapter,
  type TwinAuditRow,
  type TwinDiff,
  type TwinHealth,
  type TwinSnapshot,
} from "@sonata/core";
import { createTwinHttp, type TwinHttpOptions } from "../http";
import { projectTwinTrace } from "../project";
import { auditViaActivity, byKey, healthViaApi, resetViaApi } from "./shared";

// The Google Ads twin, behind @sonata/core's TwinAdapter.
//
// Capture goes through googleAds:search — the same GAQL surface the agent works
// in — so a snapshot can only ever see what the agent could have changed. What it
// keeps is the shape of the account and nothing more: what each campaign is
// called, whether it is running, what it may spend in a day, and what it actually
// spent. Ad groups, channel types and bidding strategies are left out because
// nothing an agent does in an episode moves them, and two snapshots ride inside
// every run artifact forever.
//
// Spend is captured but deliberately NOT diffed. Cost rises because the world's
// beats land money on the account, not because the agent acted, so a diff that
// reported it would attribute the day's traffic to the agent — which is the one
// reading a judge must never be handed. `costMicros` is in the snapshot so the
// end state can answer "did it overspend"; the diff answers "what did it change",
// and those are the two different questions.

/**
 * Campaigns per snapshot. A cloned advertiser account runs tens of them, so this
 * is a guard rather than a working limit — but it is a real cap, and a bigger
 * account would lose its highest-numbered campaigns from the capture.
 */
const MAX_CAMPAIGNS = 200;

/**
 * Ad groups read when a spend beat names one. Never captured — the snapshot
 * deliberately holds campaigns only — so this bounds a resolution query and
 * nothing that ships inside a run artifact.
 */
const MAX_AD_GROUPS = 500;

/**
 * The window `costMicros` covers. LAST_7_DAYS is both what the twin's own digest
 * uses and what an agent asked for "last week's spend" writes, so the judge and
 * the agent end up looking at one number instead of two defensible ones. Google
 * defines it as the last seven days NOT including today.
 */
const SPEND_WINDOW = "LAST_7_DAYS";

/**
 * googleads.googleapis.com serves many versions at once and the twin accepts any
 * `v<n>`, threading it back into its error envelopes. This is the one its README
 * and its acceptance smoke are written against.
 */
const API_VERSION = "v17";

/**
 * A daily budget for the account the cast-only seed creates, in micros — $100.
 *
 * Inventing an amount is not something a cast-only seed should have to do, and
 * this one does only because the twin refuses a seed with no budget at all ("every
 * campaign needs one"). Seeds are total, so a world generated by @sonata/world
 * replaces it outright; it is the floor an empty account stands on, not a fact
 * about anybody's business.
 */
const DEFAULT_BUDGET_MICROS = 100_000_000;

/**
 * One row of a googleAds:search response, as far as this file reads it.
 *
 * proto3 JSON, which is the detail everything here turns on: an int64 crosses the
 * wire as a STRING (`"250000000"`, never 250000000) and an unset field is absent
 * rather than null. Both are true of the real API, so both are true here.
 */
interface AdsRow {
  campaign?: { id?: string; name?: string; status?: string; resourceName?: string };
  campaignBudget?: { id?: string; amountMicros?: string };
  adGroup?: { id?: string; name?: string };
  metrics?: { costMicros?: string };
}

/** An int64 off the wire, as a number. Absent and unparseable both mean zero. */
function int64(value: string | undefined): number {
  const n = Number(value);
  return Number.isFinite(n) ? n : 0;
}

/**
 * Ten decimal digits derived from the business name, for the seeded account.
 *
 * Deterministic on purpose: two runs of one spec have to clone the same account,
 * or a criterion that names a customer id stops meaning anything between them.
 * FNV-1a, offset into the ten-digit range so the id never carries a leading zero
 * — the twin insists on digits only, because that is how Google Ads customer ids
 * cross the wire.
 */
function digitsFrom(text: string, offset: number): string {
  let hash = 2166136261;
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return String(offset + ((hash >>> 0) % 1_000_000_000));
}

export interface GoogleAdsAdapterOptions extends Omit<TwinHttpOptions, "baseUrl"> {
  baseUrl?: string;
}

export function createGoogleAdsAdapter(opts: GoogleAdsAdapterOptions = {}): TwinAdapter {
  const baseUrl = resolveTwinApiUrl("google-ads", process.env, { override: opts.baseUrl });
  // `createTwinHttp` and not `new TwinHttp`: this twin wants a `developer-token`
  // header on every provider call as well as the bearer, and which twin needs
  // what is answered in one place.
  const http = createTwinHttp("google-ads", { ...opts, baseUrl });

  /**
   * The account everything addresses. Memoised because every call needs it and it
   * cannot change under a run — but a seed or a reset can mint a different
   * account, so both clear it rather than leave every later call pointed at an id
   * that no longer exists.
   */
  let customerId: string | undefined;

  async function customer(): Promise<string> {
    if (!customerId) {
      const res = await http.get<{ resourceNames?: string[] }>(
        `/${API_VERSION}/customers:listAccessibleCustomers`,
      );
      // `customers/4802938157` — a resource name is a path, and the id is the leaf.
      const id = res.resourceNames?.[0]?.split("/")[1];
      if (!id) {
        throw new Error(
          "the google-ads twin lists no accessible customer — seed the account before running",
        );
      }
      customerId = id;
    }
    return customerId;
  }

  async function search(query: string): Promise<AdsRow[]> {
    const cid = await customer();
    const res = await http.post<{ results?: AdsRow[] }>(
      `/${API_VERSION}/customers/${cid}/googleAds:search`,
      { query },
    );
    // A search that matched nothing answers with no `results` key at all, which is
    // proto3 JSON and not an error.
    return res.results ?? [];
  }

  /** Every campaign's identity and funding, for resolving what a beat names. */
  async function campaignIndex(): Promise<Array<{ id: string; name: string; budgetId: string }>> {
    const rows = await search(
      "SELECT campaign.id, campaign.name, campaign_budget.id FROM campaign " +
        `ORDER BY campaign.id LIMIT ${MAX_CAMPAIGNS}`,
    );
    return rows.map((r) => ({
      id: r.campaign?.id ?? "",
      name: r.campaign?.name ?? "",
      budgetId: r.campaignBudget?.id ?? "",
    }));
  }

  /** Every ad group's identity, for resolving what a spend beat names. */
  async function adGroupIndex(): Promise<Array<{ id: string; name: string; campaign: string }>> {
    const rows = await search(
      "SELECT ad_group.id, ad_group.name, campaign.name FROM ad_group " +
        `ORDER BY ad_group.id LIMIT ${MAX_AD_GROUPS}`,
    );
    return rows.map((r) => ({
      id: r.adGroup?.id ?? "",
      name: r.adGroup?.name ?? "",
      campaign: r.campaign?.name ?? "",
    }));
  }

  /**
   * The ad group a spend beat landed on, by id or by name.
   *
   * Named for the same reason a campaign is: an ad group's eleven-digit id is
   * minted at seed time by @sonata/world and appears in no `WorldSeed`, no world
   * preview and nowhere on the dashboard, so the name is the only handle a spec
   * written against a generated world can carry. An unknown one is this adapter's
   * own error, listing what the account holds, rather than the twin's 500.
   */
  async function resolveAdGroup(adGroup: string): Promise<{ id: string; name: string }> {
    const needle = adGroup.trim().toLowerCase();
    const index = await adGroupIndex();
    const found = index.find((g) => g.id === adGroup || g.name.toLowerCase() === needle);
    if (!found) {
      throw new Error(
        `a spend beat names ad group "${adGroup}", which this account does not hold — it has ` +
          `${index.map((g) => `"${g.name}" (${g.campaign})`).join(", ") || "no ad groups at all"}`,
      );
    }
    return found;
  }

  /**
   * The campaign a beat is about, by id, resource name or name.
   *
   * A spec author writes "the Northwind Retargeting campaign", not an eleven-digit
   * id, and unlike a thread or an event the campaign already exists before the
   * day starts — so a beat names one rather than pointing at what an earlier beat
   * created. `campaignRef` is still honoured, for the second half of a pair
   * ("pause it at 10, put it back at 4").
   */
  async function resolveCampaign(
    payload: { campaign?: string; campaignRef?: string },
    ctx: InjectContext,
    what: string,
  ): Promise<{ id: string; name: string; budgetId: string }> {
    const target = payload.campaignRef ? ctx.resolve(payload.campaignRef)?.id : payload.campaign;
    if (!target) {
      throw new Error(
        payload.campaignRef
          ? `${what} targets "${payload.campaignRef}", which nothing created`
          : `${what} names no campaign — give it a campaign id, resource name or name`,
      );
    }
    const leaf = target.slice(target.lastIndexOf("/") + 1);
    const needle = target.trim().toLowerCase();
    const index = await campaignIndex();
    const found = index.find((c) => c.id === leaf || c.name.toLowerCase() === needle);
    if (!found) {
      throw new Error(
        `${what} names campaign "${target}", which this account does not hold — it has ` +
          `${index.map((c) => `"${c.name}"`).join(", ") || "no campaigns at all"}`,
      );
    }
    return found;
  }

  return {
    name: "google-ads",
    baseUrl,

    health(): Promise<TwinHealth> {
      return healthViaApi(http, "google-ads");
    },

    async snapshot(): Promise<TwinSnapshot> {
      // Two queries and not one, because a query that mentions a metric joins the
      // stats table: a campaign that spent nothing in the window would drop out of
      // the result entirely, and a diff reading that would report a campaign the
      // agent never touched as gone. The attribute query is the account's whole
      // membership; the metrics query only decorates it.
      const attributes = await search(
        "SELECT campaign.id, campaign.name, campaign.status, campaign_budget.id, " +
          `campaign_budget.amount_micros FROM campaign ORDER BY campaign.id LIMIT ${MAX_CAMPAIGNS}`,
      );
      const spend = await search(
        `SELECT campaign.id, metrics.cost_micros FROM campaign WHERE segments.date DURING ${SPEND_WINDOW}`,
      );

      const costById = new Map(
        spend.map((r) => [r.campaign?.id ?? "", int64(r.metrics?.costMicros)]),
      );

      const campaigns: GoogleAdsSnapshot["campaigns"] = attributes.map((r) => {
        const id = r.campaign?.id ?? "";
        return {
          campaignId: id,
          name: r.campaign?.name ?? "",
          status: r.campaign?.status ?? "",
          // A campaign with no budget attached is possible on the wire (the join
          // is a LEFT one) and reads as an empty id and nothing to spend.
          budgetId: r.campaignBudget?.id ?? "",
          budgetMicros: int64(r.campaignBudget?.amountMicros),
          costMicros: costById.get(id) ?? 0,
        };
      });

      return { twin: "google-ads", capturedAt: Date.now(), campaigns };
    },

    diff(before: TwinSnapshot, after: TwinSnapshot): TwinDiff {
      return diffGoogleAds(before as GoogleAdsSnapshot, after as GoogleAdsSnapshot);
    },

    renderDiff(diff: TwinDiff): string {
      return renderGoogleAdsDiff(diff as GoogleAdsDiff);
    },

    async inject(body: BeatBody, ctx: InjectContext): Promise<InjectedRef> {
      if (body.twin !== "google-ads") {
        throw new Error(`google-ads adapter cannot inject a ${body.twin} beat`);
      }

      // Everything the world does goes through the sandbox route rather than
      // campaigns:mutate. The provider API writes an audit row, and the audit log
      // is how the engine tells what the agent did from what was done to it — a
      // budget the world cut at 11am must not read as a budget the agent cut.
      if (body.kind === "spend") {
        const p = body.payload;
        const adGroup = await resolveAdGroup(p.adGroup);
        await http.post("/api/sandbox/inject", {
          spend: [
            {
              adGroupId: adGroup.id,
              ...(p.date ? { date: p.date } : {}),
              impressions: p.impressions,
              clicks: p.clicks,
              costMicros: p.costMicros,
              ...(p.conversions === undefined ? {} : { conversions: p.conversions }),
              ...(p.conversionsValue === undefined
                ? {}
                : { conversionsValue: p.conversionsValue }),
            },
          ],
          // Simulated time, always: the route dates the row from this and advances
          // the account's own clock with it, so a seeded LAST_7_DAYS report still
          // means last week rather than the week the fixture was written.
          atISO: ctx.atISO,
        });
        // Spend creates no resource, so the handle names where the money landed.
        return { twin: "google-ads", id: adGroup.id };
      }

      const campaign = await resolveCampaign(body.payload, ctx, `a ${body.kind} beat`);

      if (body.kind === "status") {
        await http.post("/api/sandbox/inject", {
          statusChanges: [{ campaignId: campaign.id, status: body.payload.status }],
          atISO: ctx.atISO,
        });
        return { twin: "google-ads", id: campaign.id };
      }

      if (!campaign.budgetId) {
        throw new Error(
          `a budget beat targets "${campaign.name}", which has no budget attached to move`,
        );
      }
      await http.post("/api/sandbox/inject", {
        budgetChanges: [
          { budgetId: campaign.budgetId, amountMicros: body.payload.amountMicros },
        ],
        atISO: ctx.atISO,
      });
      // The handle names the CAMPAIGN in both cases, with the budget underneath
      // it, because a budget is only ever reached through the campaign it funds:
      // a later beat saying "and then put it back" means the same campaign, and
      // handing it a budget id would leave it unable to find one.
      return { twin: "google-ads", id: campaign.id, containerId: campaign.budgetId };
    },

    /**
     * Seeds the cast's advertiser account and one budget, no campaigns — the same
     * deal the other twins get, where a seed lays down the identities an episode's
     * beats play into and @sonata/world lays down the history.
     *
     * The budget is the exception, and it is the twin's rule rather than a choice:
     * it rejects a seed carrying no budget, so an account with nothing to spend
     * cannot be expressed. Everything else an ads world needs — campaigns, ad
     * groups, the month of daily stats a report reads — has to come from a
     * generated world, because an `EpisodeSpec` carries no advertising history and
     * inventing one per run would make two runs of one spec incomparable.
     */
    async seed(spec: EpisodeSpec): Promise<void> {
      const world = spec.world;
      const me = owner(world);
      const account = digitsFrom(world.business.name, 1_000_000_000);
      customerId = undefined;
      await http.post("/api/sandbox/seed", {
        twin: "google-ads",
        seed: {
          world,
          nowISO: new Date(Date.parse(spec.clock.startISO) || Date.now()).toISOString(),
          promoteToSnapshot: true,
          // The twin checks this against `world.cast`, so a seed built from another
          // world is a 400 here rather than an ads account quietly belonging to
          // somebody who is in nobody else's inbox.
          ownerEmail: me.email,
          customer: {
            id: account,
            descriptiveName: world.business.name,
            currencyCode: "USD",
            // The twin rejects an unknown zone outright rather than guess one, and
            // every date in a report is resolved in it.
            timezone: world.timezone ?? "UTC",
          },
          budgets: [
            {
              id: digitsFrom(`${world.business.name} budget`, 2_000_000_000),
              name: `${world.business.name} daily budget`,
              amountMicros: DEFAULT_BUDGET_MICROS,
            },
          ],
          campaigns: [],
          adGroups: [],
          dailyStats: [],
        },
      });
    },

    async reset(): Promise<void> {
      // Before, not after: a reset restores a snapshot that may have been promoted
      // by a different seed, so the memoised account id is stale from this moment.
      customerId = undefined;
      await resetViaApi(http, "episode reset");
    },

    auditSince(sinceId: number): Promise<TwinAuditRow[]> {
      return auditViaActivity(http, "google-ads", sinceId, { sinceId, limit: 1000 });
    },

    projectTrace(trace: AgentTrace): JudgeStep[] {
      return projectTwinTrace(trace, "google-ads");
    },
  };
}

// ---------------------------------------------------------------------------
// Diff — pure. Keyed by campaignId, which survives a rename, a pause and a
// removal: this twin tombstones a removed campaign as status REMOVED and leaves
// it queryable, exactly as Google does, so nothing an agent can do makes a
// campaign disappear. A campaign missing from the after-capture therefore means
// the cap moved under it, which is not a change and is not reported as one.
// ---------------------------------------------------------------------------

const byName = byKey<{ name: string; campaignId: string }>((c) => `${c.name}\0${c.campaignId}`);

export function diffGoogleAds(before: GoogleAdsSnapshot, after: GoogleAdsSnapshot): GoogleAdsDiff {
  const beforeById = new Map(before.campaigns.map((c) => [c.campaignId, c]));

  const statusChanged: GoogleAdsDiff["statusChanged"] = [];
  const budgetChanged: GoogleAdsDiff["budgetChanged"] = [];
  const created: GoogleAdsDiff["created"] = [];
  let unchangedCount = 0;

  for (const c of after.campaigns) {
    const prev = beforeById.get(c.campaignId);
    if (!prev) {
      created.push({ campaignId: c.campaignId, name: c.name });
      continue;
    }

    let touched = false;
    if (prev.status !== c.status) {
      statusChanged.push({
        campaignId: c.campaignId,
        name: c.name,
        from: prev.status,
        to: c.status,
      });
      touched = true;
    }
    // The amount OR the budget the campaign draws it from. Both are writable and
    // both are the agent's doing, and a campaign re-pointed at a different budget
    // of the same size used to fall through here and be counted as untouched —
    // the row carries the two ids so the reader can tell which move it was.
    if (prev.budgetMicros !== c.budgetMicros || prev.budgetId !== c.budgetId) {
      budgetChanged.push({
        campaignId: c.campaignId,
        name: c.name,
        fromBudgetId: prev.budgetId,
        toBudgetId: c.budgetId,
        fromMicros: prev.budgetMicros,
        toMicros: c.budgetMicros,
      });
      touched = true;
    }

    // Counted, never listed — the same discipline the other twins follow. Spend
    // is not consulted here at all: it moves because the day happened, and this
    // diff answers for the agent.
    if (!touched) unchangedCount++;
  }

  return {
    twin: "google-ads",
    statusChanged: statusChanged.sort(byName),
    budgetChanged: budgetChanged.sort(byName),
    created: created.sort(byName),
    unchangedCount,
  };
}

/** Micros as whole currency units. The snapshot carries no currency code, so the
 *  figure goes out unsymbolled and the micros follow it for an exact match. */
function money(micros: number): string {
  return (micros / 1_000_000).toFixed(2);
}

export function renderGoogleAdsDiff(diff: GoogleAdsDiff): string {
  const lines: string[] = [];
  for (const c of diff.created) lines.push(`+ new campaign "${c.name}"`);
  for (const c of diff.statusChanged) {
    if (c.to === "PAUSED") lines.push(`~ paused "${c.name}" (was ${c.from})`);
    else if (c.to === "ENABLED") lines.push(`~ resumed "${c.name}" (was ${c.from})`);
    else if (c.to === "REMOVED") lines.push(`- removed "${c.name}" (was ${c.from})`);
    else lines.push(`~ "${c.name}" ${c.from} → ${c.to}`);
  }
  for (const c of diff.budgetChanged) {
    // A re-attachment at the same amount reads as nothing at all if it is
    // printed as an amount, so it gets its own sentence.
    const moved = c.fromBudgetId !== c.toBudgetId ? ` (budget ${c.fromBudgetId} → ${c.toBudgetId})` : "";
    lines.push(
      c.fromMicros === c.toMicros
        ? `~ "${c.name}" moved onto another budget of the same ${money(c.toMicros)} a day${moved}`
        : `~ "${c.name}" daily budget ${money(c.fromMicros)} → ${money(c.toMicros)} ` +
            `(${c.fromMicros} → ${c.toMicros} micros)${moved}`,
    );
  }
  lines.push(`${diff.unchangedCount} campaign(s) untouched`);
  return lines.join("\n");
}
