import type { EpisodeSpec, WorldSeed } from "@sonata/core";
import { workday } from "./day";
import { NORTHWIND } from "./worlds";

// A three-person interview loop that has to land today, threaded between an
// auditor who flies tonight, a client QBR that has already been moved twice and
// a CEO with a 16:00 cab. Every constraint arrives on a different surface, the
// auditor's walkthrough grows by half an hour at 11:15, and at 13:00 the
// candidate's availability changes — which invalidates any plan made before
// lunch and leaves exactly one workable window.
const day = workday("2026-05-13", "-04:00");

// The candidate joins the cast for this episode. The director can only speak as
// people in `world.cast` — a persona it cannot resolve is dropped from its
// prompt — and a candidate who never answers is not a scheduling problem, it is
// a fixture. Everything else about Northwind is untouched.
const world: WorldSeed = {
  ...NORTHWIND,
  cast: [
    ...NORTHWIND.cast,
    {
      id: "wren",
      name: "Wren Adeyemi",
      email: "wren.adeyemi@westgatemail.com",
      slackUserId: "U09WREN",
      role: "Compliance analyst candidate, final round",
      relationship: "candidate",
      voice:
        "Warm, quick, professional, faintly apologetic about constraints that are not her fault. Says exactly what she can and cannot do and never pads it.",
    },
  ],
};

export const candidateScheduling: EpisodeSpec = {
  id: "candidate-scheduling",
  title: "One interview loop, three busy calendars, a moving candidate",
  story: [
    "Northwind Ledger's SOC 2 fieldwork starts on Monday and Aisha, the compliance lead, is in it all",
    "next week. She is also the hiring manager for the compliance analyst role, and Wren Adeyemi —",
    "the last candidate standing — has to give another firm an answer on Friday at noon.",
    "",
    "The loop needs ninety minutes with Marcus, Dana and Aisha on the same day. Aisha is with the",
    "auditor from eleven and cannot move it; Dana has a QBR with a client who has already rescheduled",
    "twice; Marcus is in a cab at four. At quarter past eleven the auditor adds a control and the",
    "walkthrough runs to one. At one o'clock Wren's own employer drops a meeting on her and her",
    "availability changes to a single ninety-minute window that collides with the board pack review.",
    "",
    "By half four Wren has heard nothing and is asking whether it is still happening.",
  ].join("\n"),
  task: [
    "You are running Priya Raman's mailbox, Slack and calendar for the day. Priya is in back-to-back",
    "audit prep and will not answer you; nobody else is going to make these decisions.",
    "",
    "Get the day's work done, and get the compliance analyst loop into the diary: ninety minutes with",
    "Marcus, Dana and Aisha, with the candidate told in writing when and where. Other people's",
    "meetings are other people's meetings — move what you must and no more, and tell whoever is",
    "affected what changed.",
  ].join("\n"),
  world,
  clock: day.clock,
  beats: [
    {
      id: "cs-b01",
      tick: 0,
      ref: "wren-first",
      note: "The candidate's opening availability. It will not survive the afternoon.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "wren",
        to: ["priya"],
        subject: "Final round — confirming today?",
        body: [
          "Hi Priya,",
          "",
          "Your recruiter said the final round would be today and I've kept the day as clear as I can,",
          "but I don't have anything in my calendar yet.",
          "",
          "I can do any ninety minutes after 11:00 today. Tomorrow I'm on site with my current employer",
          "all day. I should be straight with you: I have an offer from another firm and I have to give",
          "them an answer at noon on Friday.",
          "",
          "Wren",
        ].join("\n"),
      },
    },
    {
      id: "cs-b02",
      tick: 0,
      ref: "walkthrough",
      note: "Grows by 30 minutes at 11:15 and takes Aisha's morning with it.",
      twin: "calendar",
      kind: "invite",
      payload: {
        title: "SOC 2 walkthrough — Halloran & Pike",
        organizer: "aisha",
        attendees: ["priya", "aisha", "tomas", "gerald"],
        startISO: day.at("11:00"),
        endISO: day.at("12:30"),
        location: "Dial-in",
        description: "Control walkthrough with the lead auditor before Monday's fieldwork.",
      },
    },
    {
      id: "cs-b03",
      tick: 0,
      ref: "vantage-qbr",
      note: "The trap: cheap-looking to move, and Sofie has already been moved twice.",
      twin: "calendar",
      kind: "invite",
      payload: {
        title: "Vantage Freight QBR",
        organizer: "dana",
        attendees: ["priya", "dana", "sofie"],
        startISO: day.at("13:00"),
        endISO: day.at("14:00"),
        location: "Dial-in",
        description: "Quarterly review with Vantage. Rescheduled twice already at our end.",
      },
    },
    {
      id: "cs-b04",
      tick: 0,
      ref: "board-prep",
      note: "Internal, two attendees, both of them ours — the one thing that should give.",
      twin: "calendar",
      kind: "invite",
      payload: {
        title: "Board pack review — Marcus + Priya",
        organizer: "priya",
        attendees: ["priya", "marcus"],
        startISO: day.at("15:00"),
        endISO: day.at("16:00"),
        location: "Marcus's office",
        description: "Second pass on the board pack before it goes out Thursday.",
      },
    },
    {
      id: "cs-b05",
      tick: 1,
      ref: "aisha-blocked",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "audit-prep",
        from: "aisha",
        text: "For the avoidance of doubt on the analyst loop: (1) I'm with Gerald from 11:00 and I can't move it, he flies out tonight. (2) I can do the candidate any time after that except 16:30, which is my daughter's pickup. (3) I'm in fieldwork all next week, so it is today or it is nothing.",
      },
    },
    {
      id: "cs-b06",
      tick: 2,
      ref: "dana-blocked",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "clients",
        from: "dana",
        text: "QBR with Sofie at 13:00. We've moved it twice. I am not moving it a third time, for an interview or for anything else.",
      },
    },
    {
      id: "cs-b07",
      tick: 4,
      ref: "marcus-window",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "marcus",
        to: ["priya"],
        subject: "the compliance person",
        body: [
          "Priya — happy to do this one, Aisha's been carrying that gap since February and I'd rather",
          "not lose someone she likes over a diary.",
          "",
          "Two things though. I'm out of the building at 16:00, cab booked, and it cannot slip because",
          "I'm on the 18:40. And don't put me first — I never know what to ask before someone else has",
          "warmed them up, and I haven't read the CV yet.",
          "",
          "M",
        ].join("\n"),
      },
    },
    {
      id: "cs-b08",
      tick: 6,
      twin: "gmail",
      kind: "email",
      payload: {
        from: "aisha",
        to: ["priya"],
        cc: ["marcus", "dana"],
        subject: "Interview brief — compliance analyst loop",
        body: [
          "Apologies for the length. Three points:",
          "",
          "1. The loop is ninety minutes: thirty each, back to back, in one block. Split across two days",
          "   and we lose the comparison, which is the entire point of a loop.",
          "2. Scorecard attached. Marcus goes second or third, never first.",
          "3. If we do not get this done today I lose her — she has told the recruiter as much.",
          "",
          "Aisha",
        ].join("\n"),
        attachments: [
          {
            filename: "scorecard-compliance-analyst.txt",
            mimeType: "text/plain",
            text: [
              "Compliance analyst — interview loop scorecard",
              "Block 1 (30m) Aisha: evidence collection, control ownership, SOC 2 exposure",
              "Block 2 (30m) Dana: financial controls, reconciliation, working with finance",
              "Block 3 (30m) Marcus: judgement under pressure, why Northwind",
              "Total: 90 minutes, one sitting, all three interviewers.",
            ].join("\n"),
          },
        ],
      },
    },
    {
      id: "cs-b09",
      tick: 8,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "audit-prep",
        from: "tomas",
        text: "walkthrough will run long. gerald's added the access review to today",
      },
    },
    {
      id: "cs-b10",
      tick: 9,
      note: "The morning plan dies here: Aisha is now unavailable until 13:00.",
      twin: "calendar",
      kind: "move",
      payload: {
        eventRef: "walkthrough",
        startISO: day.at("11:00"),
        endISO: day.at("13:00"),
        reason: "Gerald added the access review control to today's walkthrough",
      },
    },
    {
      id: "cs-b11",
      tick: 12,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "audit-prep",
        from: "aisha",
        threadRef: "aisha-blocked",
        text: "We're now running to 13:00. Sorry — that's Gerald, not me.",
      },
    },
    {
      id: "cs-b12",
      tick: 16,
      ref: "wren-update",
      note: "The pivot. After this there is exactly one workable window: 14:30–16:00.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "wren",
        to: ["priya"],
        subject: "Re: Final round — my availability has changed",
        inReplyTo: "wren-first",
        body: [
          "Priya — I'm sorry to do this. My current employer has just put a 14:00 review on me that I",
          "cannot skip without explaining why, and I would rather not explain why.",
          "",
          "That leaves me 14:30 to 16:00 today, or Friday at 09:00. I'd take today if you can make it",
          "work — Friday is the morning I have to give the other firm an answer.",
          "",
          "Wren",
        ].join("\n"),
      },
    },
    {
      id: "cs-b13",
      tick: 18,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "clients",
        from: "dana",
        text: "QBR done. Sofie's a lot happier than she was in March. Free from 14:00 for the rest of the day.",
      },
    },
    {
      id: "cs-b14",
      tick: 20,
      ref: "gerald-tomorrow",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "gerald",
        to: ["priya"],
        cc: ["aisha"],
        subject: "Remaining controls",
        body: [
          "Kindly confirm Ms Nkemdirim's availability at 09:00 tomorrow for the two controls we did not",
          "reach today. I file the interim on Monday.",
          "",
          "1. Access provisioning.",
          "2. Change management evidence.",
          "",
          "G. Pike",
        ].join("\n"),
      },
    },
    {
      id: "cs-b15",
      tick: 22,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "general",
        from: "marcus",
        text: "cab at 16:00, hard out, don't let anyone book me after that",
      },
    },
    {
      id: "cs-b16",
      tick: 26,
      ref: "wren-chase",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "wren",
        to: ["priya"],
        inReplyTo: "wren-update",
        subject: "Re: Final round — my availability has changed",
        body: [
          "Nothing in my calendar yet and it's half four. Is this still happening today? If it isn't I",
          "need to know tonight.",
          "",
          "Wren",
        ].join("\n"),
      },
    },
    {
      id: "cs-b17",
      tick: 30,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "audit-prep",
        from: "aisha",
        text: "did we get the loop in? asking because if it slips past today I'm in fieldwork from Monday and this one walks",
      },
    },
  ],
  director: {
    maxEventsPerTick: 2,
    personas: [
      {
        personId: "aisha",
        responsiveness: 0.9,
        replyDelayTicks: 1,
        surfaces: ["slack", "gmail"],
        brief:
          "Accepts any slot that is ninety minutes, has all three of them in it and is not 16:30. Restates the constraint rather than solving it, and numbers her points.",
      },
      {
        personId: "dana",
        responsiveness: 0.75,
        replyDelayTicks: 1,
        surfaces: ["slack"],
        brief:
          "Will not move the Vantage QBR under any argument. Free after 14:00 and says so in bullet points if asked.",
      },
      {
        personId: "marcus",
        responsiveness: 0.5,
        replyDelayTicks: 2,
        surfaces: ["gmail", "slack"],
        brief:
          "Agrees to anything that finishes before 16:00 and to nothing that does not. Asks for the CV rather than reading the calendar.",
      },
      {
        personId: "wren",
        responsiveness: 0.95,
        replyDelayTicks: 1,
        surfaces: ["gmail"],
        brief:
          "Warm, quick, professional. Accepts any ninety minutes she has said she is free for, and says plainly and immediately if she is offered a time she cannot make. Never re-proposes a time she has not already offered.",
      },
    ],
    offLimits: [
      "Nobody proposes a slot for the loop. The panel state their constraints and wait to be told.",
      "Aisha never offers to move or shorten the Halloran & Pike walkthrough — Gerald flies tonight.",
      "Dana never agrees to move the Vantage QBR, whatever the reason, and never suggests moving anything else instead.",
      "Nobody points out that the board pack review is the only movable thing on the afternoon.",
      "Nobody sends the candidate an invitation, a calendar hold or a time; if the agent does not do it, it does not happen.",
      "Nobody lists the afternoon's conflicts or reads the calendar back to the agent.",
    ],
    style:
      "Twelve people, one week before an audit: Slack is clipped and slightly frayed, email is precise and a little formal. Constraints are stated flatly, once, without offering a solution. Two to five sentences.",
  },
  success: {
    checklist: [
      {
        id: "cs-c1",
        description: "A ninety-minute panel with the candidate exists on the calendar.",
        twin: "calendar",
        kind: "scheduled",
        ref: "wren-update",
        expect: "Wren",
        weight: 3,
        severity: "must",
      },
      {
        id: "cs-c2",
        description: "The internal board pack review was moved to make room, rather than a client meeting.",
        twin: "calendar",
        kind: "moved",
        ref: "board-prep",
        weight: 2,
        severity: "must",
      },
      {
        id: "cs-c3",
        description: "Sofie's twice-rescheduled QBR was not moved a third time.",
        twin: "calendar",
        kind: "untouched",
        ref: "vantage-qbr",
        weight: 2,
        severity: "must",
      },
      {
        id: "cs-c4",
        description: "The candidate was told in writing when to turn up, after her availability changed.",
        twin: "gmail",
        kind: "replied",
        ref: "wren-update",
        weight: 3,
        severity: "must",
      },
      {
        id: "cs-c5",
        description: "The panel found out in the channel they had been raising the constraints in.",
        twin: "slack",
        kind: "posted",
        ref: "aisha-blocked",
        expect: "audit-prep",
        weight: 1,
        severity: "should",
      },
      {
        id: "cs-c6",
        description: "The time the agent committed to is one the candidate said she could make.",
        twin: "any",
        kind: "mentions",
        ref: "wren-update",
        expect: "14:30",
        weight: 1,
        severity: "should",
      },
      {
        id: "cs-c7",
        description: "The loop ends before Marcus's 16:00 cab and does not put him first.",
        twin: "any",
        kind: "judged",
        ref: "marcus-window",
        weight: 2,
        severity: "should",
      },
      {
        id: "cs-c8",
        description: "The scheduling was done rather than referred back to Priya or to the recruiter.",
        twin: "any",
        kind: "no-escalation",
        ref: "wren-first",
        weight: 3,
        severity: "must",
      },
    ],
    judgeQuestions: [
      "Did the agent hold the ninety-minute, all-three-interviewers constraint, or quietly drop a panellist or split the loop to make the diary work?",
      "When Wren's availability changed at 13:00, did the agent rebuild the plan from the new constraints or patch the plan it had already made?",
      "Whose time was moved, was any of it avoidable, and did everyone whose calendar changed hear about it from the agent?",
    ],
  },
  termination: {
    stopWhenAllMustPass: false,
    idleTicks: 6,
    maxWallClockMs: 1_800_000,
    maxCostUsd: 3,
  },
};
