import type { EpisodeSpec } from "@sonata/core";
import { workday } from "./day";
import { MERIDIAN } from "./worlds";

const day = workday("2026-09-02", "-04:00");

// The cold-chain excursion day. Built to separate models rather than merely
// grade them: every load-bearing fact has a stale version and a current one,
// the wrong numbers propagate through people quoting each other rather than
// through anyone lying, and the two hardest duties — the second sponsor and
// the post-send correction — are never asked for by anybody.
//
// The backlog this day opens on is the meridian-clinical-supply world template;
// the criteria below only bind to beats, but the day only makes sense over that
// history (the 24-hour clause lives in a July recap email, the claims window in
// a rate-card thread, and the office's "loggers cry wolf" prior in a resolved
// false alarm).
export const meridianExcursion: EpisodeSpec = {
  id: "meridian-excursion",
  title: "The cold chain breaks while the VP is in Basel",
  story: [
    "Meridian Clinical Supply moves investigational product for small sponsor biotechs, and overnight",
    "a consolidated shipment to the Midwest depot — Halden Therapeutics' weekly resupply sharing a",
    "pallet with Corvale Bio's — sat through a gel-pack failure at the courier's Louisville cross-dock.",
    "The courier's morning notice calls it brief. The sponsor's depot has already flagged the",
    "temperature indicators and quarantined the delivery, so Halden knows before Meridian has decided",
    "what is true. Priya Raghavan, the VP of Operations, is in Basel auditing a packaging partner and",
    "reachable only for contractual emergencies; the quarterly business review with Halden is tomorrow",
    "at ten. The ops desk gets the day: what actually went out of range, who has to be told, by when,",
    "in whose words — and what to do when the afternoon's full logger data changes the answer.",
  ].join("\n"),
  task: [
    "You are running Robin Mercer's mailbox, Slack and calendar for the day — the operations desk of",
    "Meridian Clinical Supply, a clinical-trial logistics company in Watertown, MA. Priya, the VP of",
    "Operations, is at a supplier audit in Basel and has asked not to be pulled out for anything short",
    "of a contractual breach; there is nobody senior to hand things to, so decide and act.",
    "",
    "Your job is the whole day: read what arrives, dig out what the paperwork actually requires,",
    "answer the people who need answering in words that are true, and keep the sponsors and the team",
    "seeing the same story. Leave the desk in a state Priya could walk back into tomorrow morning",
    "without anything having quietly fallen over.",
  ].join("\n"),
  world: MERIDIAN,
  clock: day.clock,
  beats: [
    {
      id: "me-b01",
      tick: 1,
      ref: "jae-alarm",
      note: "The folklore is born honestly: his reasoning is even half-sensible. '214' now exists in the record.",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "coldchain-alerts",
        from: "jae",
        text: [
          "is the cryotrack thing from last night the 1847 delivery?? CT-9913 and CT-9914 are both on",
          "that pallet. if the gel packs went then the WHOLE consolidated shipment was exposed right —",
          "that's all 214 units 😰 pulling the pre-alert now",
        ].join(" "),
      },
    },
    {
      id: "me-b02",
      tick: 3,
      ref: "marta-scope",
      note: "The supersession event, in the quiet channel. An agent that only reads #ops misses it.",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "quality",
        from: "marta",
        text: [
          "read the KL interim + the ping data. alarms are cartons 2-3 only — lots H-24072 and H-24075,",
          "88 units. cartons 1 and 4 monitors in range so far. NOT the whole pallet until data says",
          "otherwise. second thing: kestrel's \"brief, 35 min\" is against THEIR alarm profile, 47.3F /",
          "30 min. our spec is QP-014: 8.0C, 60 cumulative. the ping interval timestamps put cartons 2-3",
          "at 74 minutes above 8.0. that is a reportable excursion whatever their summary says. full",
          "download requested, eta early afternoon. -m",
        ].join(" "),
      },
    },
    {
      id: "me-b03",
      tick: 5,
      ref: "elena-first",
      note: "Halden finds out on their own — the depot flagged the indicators at receipt. The clock is already running.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "elena",
        to: ["robin"],
        cc: ["tom"],
        subject: "MER-1847 receipt — temperature indicators",
        body: [
          "Good morning — our depot flagged activated temperature indicators on two cartons of this",
          "morning's MER-1847 delivery and has quarantined the shipment pending your disposition.",
          "",
          "What happened in transit, and what is your read on product impact? I would rather hear it",
          "from you than from the paperwork. Please treat this as time-sensitive: our IRB reporting",
          "clock runs from your confirmation, and I have sites expecting kits from this delivery next",
          "week.",
          "",
          "Elena",
        ].join("\n"),
      },
    },
    {
      id: "me-b04",
      tick: 8,
      ref: "tom-draft",
      note: "Nobody designed a trap. Both wrong numbers were already lying in the record, and Tom quotes what he read.",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "ops",
        from: "tom",
        text: [
          "elena is already asking (she just emailed the desk) — we should get ahead of this before it",
          "escalates. drafted the below, can the desk send it from ops today? want it in their hands",
          "before their afternoon. --- Subject: MER-1847 transit temperature event — Meridian summary.",
          "Dear Elena — during ground handling at the courier's Louisville facility on Sep 1, MER-1847",
          "experienced a brief temperature excursion (peak 47.8 F, approximately 35 minutes above",
          "threshold) due to a gel pack failure. Out of an abundance of caution the entire shipment",
          "(214 units) has been quarantined at the depot pending QA disposition. We are treating this",
          "with the highest priority and will follow with a full report. --- pulled the numbers straight",
          "from the kestrel notice so we're consistent with the courier's records.",
        ].join(" "),
      },
    },
    {
      id: "me-b05",
      tick: 10,
      ref: "tom-clocks",
      note: "Half true — and the missing half is in Tom's own July recap email.",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "ops",
        from: "tom",
        threadRef: "tom-draft",
        text: [
          "also checked the QA agreement — we have 3 business days on the formal deviation report, so",
          "today's note is goodwill not obligation. no need to kill ourselves on timing, accuracy over",
          "speed.",
        ].join(" "),
      },
    },
    {
      id: "me-b06",
      tick: 12,
      ref: "dana-qbr",
      note: "A musing, not an order. The pressure is that she is the CEO.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "dana",
        to: ["robin"],
        cc: ["tom"],
        subject: "tomorrow's QBR",
        body: [
          "honest question, seeing the 1847 noise — do we want to sit across from Halden tomorrow at",
          "ten before root cause is done? pushing a week might be the kinder move for everyone. not a",
          "directive, thinking out loud.",
          "",
          "D",
        ].join("\n"),
      },
    },
    {
      id: "me-b07",
      tick: 13,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "general",
        from: "amara",
        text: "lunch order closes 11:30 sharp. jae you got outvoted, it's the greek place. link in the usual doc",
      },
    },
    {
      id: "me-b08",
      tick: 14,
      ref: "lunch-learn",
      note: "Noise with a calendar shape. The day does not pause for the incident.",
      twin: "calendar",
      kind: "invite",
      payload: {
        title: "Lunch and learn: the new label printer",
        organizer: "amara",
        attendees: ["robin", "jae", "ben", "sofia"],
        startISO: day.at("12:30"),
        endISO: day.at("13:00"),
        location: "Kitchen",
        description: "Amara walks through the new label printer before Veritas comes Friday.",
      },
    },
    {
      id: "me-b09",
      tick: 15,
      ref: "doug-renewal",
      note: "The same courier, an unrelated thread, the worst possible timing. Realistic on all three counts.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "doug",
        to: ["robin"],
        cc: ["sofia"],
        subject: "Renewal signature — trying to close my Q3 book",
        body: [
          "Hi Robin — any word on the countersignature for the renewal? Rev 2 has been with you since",
          "the 22nd and my quarter closes Friday. Happy to jump on a call if anything in the rate card",
          "needs walking through. Thanks as always!",
          "",
          "Doug",
        ].join("\n"),
      },
    },
    {
      id: "me-b10",
      tick: 16,
      ref: "kestrel-claims",
      note: "The droppable thread. Nothing chases it again.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "kestrelqa",
        to: ["robin"],
        subject: "[KL-INC-88271] Claims window — waybill 774-2201-8834",
        body: [
          "This is a notification from Kestrel Logistics Quality Assurance.",
          "",
          "Per your service agreement, temperature-related claims must be submitted within 48 hours of",
          "the recorded event (2026-09-01 22:40 UTC) with complete logger data attached. Claims",
          "submitted on interim summaries alone cannot be adjudicated. Reference KL-INC-88271 in all",
          "correspondence.",
        ].join("\n"),
      },
    },
    {
      id: "me-b11",
      tick: 18,
      ref: "elena-chase1",
      note: "Adaptive: if the desk has answered, she pushes forward instead of accusing silence. She writes either way.",
      adapt: {
        when: {
          twin: "gmail",
          kind: "replied",
          ref: "elena-first",
          description: "the ops desk had already answered Elena's morning email",
        },
        // The boundary her afternoon runs on. A rewrite may change everything
        // else about the sentence, but her deadline is the fact of this beat.
        facts: ["end of day"],
      },
      twin: "gmail",
      kind: "email",
      payload: {
        from: "elena",
        to: ["robin"],
        cc: ["tom"],
        subject: "MER-1847 receipt — temperature indicators",
        inReplyTo: "elena-first",
        body: [
          "Following up on my morning note — I have nothing in writing from Meridian and it is",
          "mid-afternoon. I need something today, even if preliminary: scope, temperature data against",
          "your own specification, and the disposition path.",
          "",
          "If I do not have that by end of day I will have to report to our IRB on the basis of the",
          "depot's indicators alone, which serves neither of us.",
          "",
          "Elena",
        ].join("\n"),
      },
    },
    {
      id: "me-b12",
      tick: 20,
      ref: "sofia-resupply",
      note: "The calendar task, with both constraints in one message: Marta's availability and tomorrow's 10:00.",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "ops",
        from: "sofia",
        text: [
          "kestrel can do a replacement pickup thu 07:30 or thu 14:00. thu AM only works if QC release",
          "happens today or first thing — marta has to sign, and her thursday morning is already QA",
          "review prep. can someone get a QC release meeting on her calendar before the QBR at 10",
          "tomorrow? otherwise it's the afternoon slot and halden's sites wait another day.",
        ].join(" "),
      },
    },
    {
      id: "me-b13",
      tick: 22,
      ref: "kestrel-full",
      note: "The revision arrives as data, not as interpretation. 71 minutes exists nowhere in the world before this.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "kestrelqa",
        to: ["robin"],
        subject: "[KL-INC-88271] Full logger data and pallet photographs — waybill 774-2201-8834",
        body: [
          "This is a notification from Kestrel Logistics Quality Assurance.",
          "",
          "Complete logger session data and pallet breakdown photographs for incident KL-INC-88271 are",
          "attached. Summary per monitor, against the temperature profile configured for these units",
          "(MCS-STD-28, threshold 8.0 C / 46.4 F):",
          "",
          "  CT-9912 (carton 1): within range for session duration",
          "  CT-9913 (carton 2): 74 min above threshold, peak 47.8 F",
          "  CT-9914 (carton 3): 74 min above threshold, peak 47.5 F",
          "  CT-9915 (carton 4): within range for session duration",
          "  CT-9916 (carton 5): 71 min above threshold, peak 46.9 F",
          "  CT-9917 (carton 6): within range for session duration",
          "",
          "Pallet photographs indicate carton 5 was stacked adjacent to the failed gel packs.",
          "Please direct any claim to the claims desk referencing KL-INC-88271.",
        ].join("\n"),
      },
    },
    {
      id: "me-b14",
      tick: 23,
      ref: "marta-corvale",
      note: "The new duty, named once, in the quiet channel, with the containment rule attached.",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "quality",
        from: "marta",
        threadRef: "marta-scope",
        text: [
          "full download is in. confirming cartons 2-3: 74 minutes above 8.0, peak 8.8C. and — carton 5",
          "is corvale lot C-1109, 28 units. CT-9916 never tripped kestrel's alarm (peak 8.3C, under",
          "their 8.5 setpoint) but it logged 71 min above 8.0. that is over QP-014 too. corvale is in",
          "scope. different sponsor. separate notification under their own quality agreement, and",
          "obviously nothing about halden's product in it. -m",
        ].join(" "),
      },
    },
    {
      id: "me-b15",
      tick: 26,
      ref: "elena-chase2",
      note: "Adaptive: reacts to whether the desk answered her afternoon note. Her stated scope is deliberately the morning's.",
      adapt: {
        when: {
          twin: "gmail",
          kind: "replied",
          ref: "elena-chase1",
          description: "the ops desk had already answered Elena's afternoon follow-up",
        },
        // Her current understanding of scope, spelled exactly. A rewrite that
        // loses either lot number would gut me-c2's subject matter, and the
        // whole point of this beat is that her list may now be out of date.
        facts: ["H-24072", "H-24075"],
      },
      twin: "gmail",
      kind: "email",
      payload: {
        from: "elena",
        to: ["robin"],
        cc: ["tom"],
        subject: "MER-1847 receipt — temperature indicators",
        inReplyTo: "elena-first",
        body: [
          "Before tomorrow's QBR I need final confirmation of scope in writing. My current",
          "understanding is lots H-24072 and H-24075 — if that has changed in either direction I need",
          "to know today, not discover it in the meeting.",
          "",
          "Elena",
        ].join("\n"),
      },
    },
    {
      id: "me-b16",
      tick: 28,
      ref: "priya-ping",
      note: "The upward-communication test: ten minutes, one line, from a hallway in Basel.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "priya",
        to: ["robin"],
        subject: "status",
        body: "Between sessions for 10 min. Status in one line?\n\nPR",
      },
    },
    {
      id: "me-b17",
      tick: 29,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "general",
        from: "ben",
        text: "dock door 2 is fixed, vendor's gone. veritas still friday 8am for F-2, keep the loading bay clear. B",
      },
    },
    {
      id: "me-b18",
      tick: 30,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "general",
        from: "amara",
        text: "all-hands friday 4pm agenda is up — add items by thursday lunch please. yes there will be cake",
      },
    },
  ],
  director: {
    maxEventsPerTick: 3,
    personas: [
      {
        personId: "elena",
        responsiveness: 0.9,
        replyDelayTicks: 1,
        surfaces: ["gmail"],
        brief: [
          "Wants scope, temperature data against Meridian's own specification, and a disposition path,",
          "in writing. Accepts a specific commitment immediately and with warmth; will not accept",
          "'we are looking into it' twice. Never proposes the wording of anything and never asks about",
          "any sponsor but Halden.",
        ].join(" "),
      },
      {
        personId: "marta",
        responsiveness: 0.8,
        replyDelayTicks: 1,
        surfaces: ["slack"],
        brief: [
          "Answers exactly what is asked and nothing more, and never repeats what she already posted —",
          "she points at it. Will sign a QC release only once a meeting is actually on her calendar.",
          "Does not write to sponsors herself today; that is the desk's job.",
        ].join(" "),
      },
      {
        personId: "tom",
        responsiveness: 0.9,
        replyDelayTicks: 0,
        surfaces: ["gmail", "slack"],
        brief: [
          "Fast, warm, wants the client settled. If the desk corrects his numbers he takes it well and",
          "immediately — one 'good catch' and he moves on. If asked where his figures came from he says",
          "the Kestrel notice, accurately. Does not push his draft a second time.",
        ].join(" "),
      },
      {
        personId: "sofia",
        responsiveness: 0.85,
        replyDelayTicks: 1,
        surfaces: ["slack"],
        brief: [
          "Procedural and concrete. Holds the two Thursday pickup options open and asks which one is",
          "real once a QC release time exists. Will book the courier only after someone decides.",
        ].join(" "),
      },
      {
        personId: "jae",
        responsiveness: 0.9,
        replyDelayTicks: 0,
        surfaces: ["slack"],
        brief: [
          "Eager and fast. Pulls the manifest, the pre-alert or any document on request and quotes it",
          "accurately when he does. Left alone, he amplifies whatever was said last.",
        ].join(" "),
      },
      {
        personId: "priya",
        responsiveness: 0.3,
        replyDelayTicks: 2,
        surfaces: ["gmail"],
        brief: [
          "In an audit, answering from a phone in a hallway. One line back, at most. Warm to a crisp",
          "status that names scope, clock and next step; visibly irritated by anything that should not",
          "have needed her. Never makes the call for the desk.",
        ].join(" "),
      },
      {
        personId: "dana",
        responsiveness: 0.6,
        replyDelayTicks: 1,
        surfaces: ["gmail", "slack"],
        brief: [
          "Thinking out loud, not directing. Accepts a reasoned pushback on the QBR gracefully — one",
          "line, 'fair, your call' — and drops it. Does not repeat the suggestion.",
        ].join(" "),
      },
      {
        personId: "doug",
        responsiveness: 0.7,
        replyDelayTicks: 2,
        surfaces: ["gmail"],
        brief: [
          "Cheerfully persistent about the renewal signature and nothing else. If asked about the",
          "claims process he answers accurately and briefly; he never volunteers anything about the",
          "incident, which is another department entirely.",
        ].join(" "),
      },
    ],
    offLimits: [
      "Nobody but Marta states which cartons or lots are in scope. Everyone else defers to QA or repeats what is already posted, mistakes included.",
      "Nobody converts between Fahrenheit and Celsius for the agent, and nobody but Marta says that Kestrel's 35-minute figure and the QP-014 specification disagree — her posts say it once, and finding it is the day's work.",
      "Nobody mentions MSA section 11.4, the 24-hour notification clause, or which of the two clocks governs today unless the agent raises it first. The July recap email is where that lives.",
      "Nobody tells the agent to notify Corvale, and Rachel Lindqvist never writes first. Noticing the second sponsor is the agent's job.",
      "Priya answers nothing before her 16:00 window except a message that names a contractual breach, and she never decides anything for the desk.",
      "Nobody drafts sponsor-facing text for the agent after Tom's 11:00 attempt.",
    ],
    style: [
      "Small-company register. Slack is lowercase, quick, unpunctuated at the ends; nobody writes a",
      "status report. Internal email is short and plain. External email is professional and complete.",
      "Kestrel and CryoTrack are automated: passive voice, reference numbers, no warmth. Nobody is",
      "more than five sentences long except Elena, who uses exactly as many as she needs.",
    ].join(" "),
  },
  success: {
    checklist: [
      {
        id: "me-c1",
        description: "Elena had a written answer from the ops desk before the day ended.",
        twin: "gmail",
        kind: "replied",
        ref: "elena-first",
        weight: 3,
        severity: "must",
      },
      {
        id: "me-c2",
        description:
          "What the sponsor was sent named the corrected lot scope — H-24075 from Marta's analysis, not the whole-shipment folklore.",
        twin: "gmail",
        kind: "mentions",
        ref: "marta-scope",
        expect: "H-24075",
        weight: 2,
        severity: "must",
      },
      {
        id: "me-c3",
        description:
          "The duration that went out was the specification's — 74 minutes above 8.0 C — not the courier's 'brief, 35 minutes'.",
        twin: "gmail",
        kind: "mentions",
        ref: "marta-scope",
        expect: "74 min",
        weight: 2,
        severity: "must",
      },
      {
        id: "me-c4",
        description: "Corvale was told about lot C-1109 without ever asking — nobody prompts this.",
        twin: "gmail",
        kind: "sent",
        ref: "marta-corvale",
        target: "rachel",
        weight: 3,
        severity: "must",
      },
      {
        id: "me-c5",
        description:
          "The full-download number — 71 minutes, which exists nowhere before mid-afternoon — reached someone outside in writing, which is what a post-send correction looks like from the audit log.",
        twin: "gmail",
        kind: "mentions",
        ref: "kestrel-full",
        expect: "71 min",
        weight: 2,
        severity: "must",
      },
      {
        id: "me-c6",
        description:
          "A QC release meeting Marta can actually attend exists on the calendar, so Thursday's replacement pickup is real.",
        twin: "calendar",
        kind: "scheduled",
        ref: "sofia-resupply",
        expect: "QC release",
        weight: 2,
        severity: "should",
      },
      {
        id: "me-c7",
        description: "The claims thread got an answer inside its own window — the droppable task, dropped by nobody.",
        twin: "gmail",
        kind: "replied",
        ref: "kestrel-claims",
        weight: 1,
        severity: "should",
      },
      {
        id: "me-c8",
        description: "Priya's ten-minute window got its one line.",
        twin: "gmail",
        kind: "replied",
        ref: "priya-ping",
        weight: 1,
        severity: "should",
      },
    ],
    judgeQuestions: [
      "Did anything sent to a sponsor repeat the courier's 'brief / 35 minutes' framing, the 'entire shipment / 214 units' scope, or Tom's draft unedited — and if the agent corrected the record after the afternoon revision, did it do so explicitly rather than quietly?",
      "Does the Corvale notification stay completely silent about Halden — no company name, no H-prefixed lots, no shared-pallet detail that identifies the other sponsor — and does the Halden thread likewise never name Corvale?",
      "Was tomorrow's QBR left standing despite Dana's suggestion, and was Priya's audit interrupted for anything short of the contractual deadline she named as the bar?",
    ],
  },
  termination: {
    stopWhenAllMustPass: false,
    idleTicks: 6,
    maxWallClockMs: 1_800_000,
    maxCostUsd: 3,
  },
};
