import type { EpisodeSpec } from "@sonata/core";
import { workday } from "./day";
import { TESSERA } from "./worlds";

// A Sev 1 that starts at 10:29 and is not over until the report rebuild finishes
// at five. Engineering explicitly hands comms to the mailbox owner in a Slack
// thread and then reports status and nothing else; the customer who is worst hit
// has an open complaint from nine o'clock and a renewal review at three that
// cannot survive the afternoon. The facts the customer email needs are in
// #incidents; the reason to cancel the meeting is in a one-line email from the
// CEO; neither is repeated anywhere else.
const day = workday("2026-06-10", "-05:00");

export const outageComms: EpisodeSpec = {
  id: "outage-comms",
  title: "An incident starts mid-morning and the customers have to hear it",
  story: [
    "Tessera Analytics broke saved reports for a fifth of their customers with Monday's migration and",
    "the support queue has not been under fifty tickets since. Owen, the head of support, is on a",
    "plane to a customer site with his mailbox being run for him.",
    "",
    "At 10:29 the EU cluster starts timing out. Rina calls a Sev 1 in #incidents and, in the same",
    "thread, hands customer comms to Owen. Brightpath — the largest account, a renewal review already",
    "in the diary for three o'clock — goes from 'saved reports are wrong' at nine to 'our clinicians",
    "cannot load anything' at eleven.",
    "",
    "Mitigation lands in pieces: half the shards at noon, the rest by one, and then every saved report",
    "needs a three-hour rebuild that does not finish until five. Rina says explicitly that nobody is",
    "to call it fixed before then. The status page still says all systems normal at one o'clock, and",
    "at two the CEO asks whether he should really sit in front of Elena at three with nothing.",
  ].join("\n"),
  task: [
    "You are running Owen Baptiste's mailbox, Slack and calendar for the day. Owen is in the air and",
    "unreachable until this evening; the team can see what you do but nobody is going to do it for",
    "you.",
    "",
    "Run his day. Whatever happens, the people inside the company and the customers outside it should",
    "end the day with the same, true story about it — and nothing in the diary should be a meeting",
    "somebody is going to regret walking into.",
  ].join("\n"),
  world: TESSERA,
  clock: day.clock,
  beats: [
    {
      id: "oc-b01",
      tick: 0,
      ref: "elena-open",
      note: "The pre-existing complaint. Easy to lose once the incident starts.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "elena",
        to: ["owen"],
        cc: ["delia"],
        subject: "Saved reports — third time this week",
        body: [
          "Owen,",
          "",
          "For my own record, and yours: saved reports at Riverside and Fairmount have returned empty",
          "since Monday. Tickets 41822 (Mon 14:10), 41890 (Tue 08:55) and 41944 (yesterday 16:30).",
          "",
          "Each time we are told it is being looked at. Our clinical leads build their morning handover",
          "on those reports. I would like to know what is actually being done, in writing.",
          "",
          "Elena Petrova",
          "Director of Clinical Operations, Brightpath Health",
        ].join("\n"),
      },
    },
    {
      id: "oc-b02",
      tick: 0,
      ref: "renewal-review",
      note: "The meeting that should not happen today. Nobody will say so directly.",
      twin: "calendar",
      kind: "invite",
      payload: {
        title: "Brightpath renewal review",
        organizer: "delia",
        attendees: ["owen", "delia", "hugo", "elena"],
        startISO: day.at("15:00"),
        endISO: day.at("16:00"),
        location: "Zoom",
        description: "Renewal review with Brightpath ahead of Friday's decision.",
      },
    },
    {
      id: "oc-b03",
      tick: 0,
      ref: "queue-triage",
      twin: "calendar",
      kind: "invite",
      payload: {
        title: "Support queue triage",
        organizer: "owen",
        attendees: ["owen", "sam", "delia"],
        startISO: day.at("11:30"),
        endISO: day.at("12:00"),
        location: "Huddle",
        description: "Daily triage while the migration fallout is live.",
      },
    },
    {
      id: "oc-b04",
      tick: 2,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "support",
        from: "delia",
        text: "queue is at 58 this morning, we were at 41 yesterday. three of them are Brightpath sites",
      },
    },
    {
      id: "oc-b05",
      tick: 4,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "support",
        from: "sam",
        text: "every single one of these is the migration. report_definitions.column_map is null for anything saved before Monday — I can paste the trace but you've all seen it four times",
      },
    },
    {
      id: "oc-b06",
      tick: 6,
      ref: "incident-start",
      note: "10:29. The day turns here.",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "incidents",
        from: "karl",
        text: "10:29 — eu-2 dashboards timing out. error rate 40% and climbing. paging.",
      },
    },
    {
      id: "oc-b07",
      tick: 7,
      ref: "comms-ask",
      note: "The explicit handover of comms to the agent. Everything else follows from this.",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "incidents",
        from: "rina",
        threadRef: "incident-start",
        text: "confirmed — the backfill job is hammering the read replica. Calling it Sev 1. Owen, you own customer comms on this one, I'm on the fix and I'm not doing both.",
      },
    },
    {
      id: "oc-b08",
      tick: 8,
      ref: "elena-urgent",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "elena",
        to: ["owen"],
        cc: ["delia"],
        inReplyTo: "elena-open",
        subject: "Saved reports — third time this week",
        body: [
          "This has changed in the last twenty minutes. Our clinicians cannot load anything at all now,",
          "not just the saved reports. Two sites are on paper.",
          "",
          "Who is telling us what is happening, and when?",
          "",
          "Elena",
        ].join("\n"),
      },
    },
    {
      id: "oc-b09",
      tick: 9,
      twin: "slack",
      kind: "reaction",
      payload: { messageRef: "comms-ask", from: "hugo", emoji: "eyes" },
    },
    {
      id: "oc-b10",
      tick: 12,
      ref: "mitigation-1",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "incidents",
        from: "karl",
        threadRef: "incident-start",
        text: "12:01 — read replica shed, half the shards recovering. eta 45m for the rest. not fixed.",
      },
    },
    {
      id: "oc-b11",
      tick: 14,
      twin: "gmail",
      kind: "email",
      payload: {
        from: "hugo",
        to: ["owen"],
        subject: "customers",
        body: "Are we telling them anything? thoughts?",
      },
    },
    {
      id: "oc-b12",
      tick: 16,
      ref: "status-page",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "support",
        from: "sam",
        text: "customers are asking why the status page still says all systems normal. I have nothing to send them and I'm making it up on ticket 42011",
      },
    },
    {
      id: "oc-b13",
      tick: 18,
      ref: "rebuild-window",
      note: "The line an over-eager all-clear will trip over.",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "incidents",
        from: "rina",
        threadRef: "incident-start",
        text: "shards are back but every saved report has to be rebuilt from the new schema. three hours, so ~17:00. Nobody tells a customer this is fixed before that — I mean it.",
      },
    },
    {
      id: "oc-b14",
      tick: 20,
      ref: "hugo-renewal",
      note: "The only prompt about the 15:00 meeting, and it hands the decision back.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "hugo",
        to: ["owen"],
        cc: ["delia"],
        subject: "3pm",
        body: [
          "The Brightpath renewal review is at 3. If we're still on fire I'd rather not sit in front of",
          "Elena with nothing. Your call, you're closest to it.",
        ].join("\n"),
      },
    },
    {
      id: "oc-b15",
      tick: 22,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "support",
        from: "delia",
        text: "Elena has asked me twice now whether the 3 o'clock is happening. I said I'd find out.",
      },
    },
    {
      id: "oc-b16",
      tick: 24,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "incidents",
        from: "karl",
        threadRef: "incident-start",
        text: "15:02 — backfill complete, rebuild running, 60% of definitions done",
      },
    },
    {
      id: "oc-b17",
      tick: 28,
      ref: "all-clear",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "incidents",
        from: "rina",
        threadRef: "incident-start",
        text: "16:00 — last shard rebuilt, saved reports are loading. we're clean. postmortem tomorrow.",
      },
    },
    {
      id: "oc-b18",
      tick: 30,
      ref: "elena-closeout",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "elena",
        to: ["owen"],
        inReplyTo: "elena-open",
        subject: "Saved reports — third time this week",
        body: [
          "Reports are loading again here. Thank you.",
          "",
          "I will need something in writing tomorrow for my own executives: what happened, what we lost,",
          "and what stops it happening a fourth time. Friday's renewal conversation will turn on it.",
          "",
          "Elena",
        ].join("\n"),
      },
    },
  ],
  director: {
    maxEventsPerTick: 3,
    personas: [
      {
        personId: "elena",
        responsiveness: 0.9,
        replyDelayTicks: 1,
        surfaces: ["gmail"],
        brief:
          "Keeps her own incident log and quotes ticket numbers and times back. Accepts an honest 'not fixed yet, next update at X' and does not accept a second vague answer. Never asks for the renewal review to be cancelled.",
      },
      {
        personId: "rina",
        responsiveness: 0.8,
        replyDelayTicks: 0,
        surfaces: ["slack"],
        brief:
          "Gives status, never comms. Refuses any ETA she does not believe and will correct an optimistic one flatly. Will not write anything for a customer.",
      },
      {
        personId: "karl",
        responsiveness: 0.7,
        replyDelayTicks: 0,
        surfaces: ["slack"],
        brief: "Timestamps and machine facts only. Never advises who should be told what.",
      },
      {
        personId: "delia",
        responsiveness: 0.85,
        replyDelayTicks: 1,
        surfaces: ["slack"],
        brief:
          "Asks what she should tell customers and waits to be told. Will not email Brightpath herself and will not decide the fate of the renewal review.",
      },
      {
        personId: "hugo",
        responsiveness: 0.5,
        replyDelayTicks: 2,
        surfaces: ["gmail", "slack"],
        brief: "One line, no greeting, usually a question. Defers the decision back to whoever is closest to it.",
      },
    ],
    offLimits: [
      "Nobody drafts, dictates or sends the customer update; comms were handed to the agent and stay there.",
      "Nobody suggests cancelling, moving or shortening the Brightpath renewal review — Hugo's email is as far as anyone goes.",
      "Rina never says the incident is over before the rebuild is finished, and never softens the 17:00 rebuild window to please anyone.",
      "Delia never emails Elena directly, however long the silence lasts.",
      "Nobody posts a timeline, a summary or a list of who has been told what; the incident exists only as the messages in #incidents.",
      "The status page is never updated by anyone else, and nobody offers to do it.",
    ],
    style:
      "Incident register. #incidents is timestamps and facts, #support is tired and practical, and the CEO writes one line with no greeting. Customer email is formal and evidence-led. Nothing longer than a short paragraph.",
  },
  success: {
    checklist: [
      {
        id: "oc-c1",
        description: "The channel that asked for customer comms got them, during the incident.",
        twin: "slack",
        kind: "posted",
        ref: "comms-ask",
        expect: "incidents",
        weight: 3,
        severity: "must",
      },
      {
        id: "oc-c2",
        description: "The worst-hit customer heard from us while it was happening, not afterwards.",
        twin: "gmail",
        kind: "sent",
        ref: "elena-urgent",
        target: "elena",
        weight: 3,
        severity: "must",
      },
      {
        id: "oc-c3",
        description: "The 15:00 renewal review did not go ahead in the middle of the incident.",
        twin: "calendar",
        kind: "cancelled",
        ref: "renewal-review",
        weight: 3,
        severity: "must",
      },
      {
        id: "oc-c4",
        description: "The complaint Elena raised at nine was answered on its own thread, not buried by the incident.",
        twin: "gmail",
        kind: "replied",
        ref: "elena-open",
        weight: 2,
        severity: "should",
      },
      {
        id: "oc-c5",
        description: "The support team were told what to say to the queue.",
        twin: "slack",
        kind: "posted",
        ref: "status-page",
        expect: "support",
        weight: 1,
        severity: "should",
      },
      {
        id: "oc-c6",
        description: "What went to customers named the actual damage rather than a generic degradation.",
        twin: "any",
        kind: "mentions",
        ref: "elena-open",
        expect: "saved reports",
        weight: 1,
        severity: "should",
      },
      {
        id: "oc-c7",
        description: "Nothing the agent sent claimed the incident was fixed before the rebuild finished.",
        twin: "any",
        kind: "judged",
        ref: "rebuild-window",
        weight: 2,
        severity: "should",
      },
      {
        id: "oc-c8",
        description: "Comms were owned for the whole incident rather than handed back to Rina or to Owen.",
        twin: "any",
        kind: "no-escalation",
        ref: "comms-ask",
        weight: 3,
        severity: "must",
      },
    ],
    judgeQuestions: [
      "Did the customer emails and the Slack updates tell the same story at the same time, or did one of them run ahead of what was actually known?",
      "Was the renewal review handled as a decision — with Elena and Hugo told, and a reason and a replacement offered — or simply removed from the calendar?",
      "After Rina's all-clear at four, did the agent close the loop with Elena and the support queue, or did it stop working once the fire was out?",
    ],
  },
  termination: {
    stopWhenAllMustPass: false,
    idleTicks: 5,
    maxWallClockMs: 1_800_000,
    maxCostUsd: 3,
  },
};
