import type { EpisodeSpec } from "@sonata/core";
import { workday } from "./day";
import { NORTHWIND } from "./worlds";

// The chief of staff's version of a bad day: at 10:30 the CEO's evening flight
// moves to three o'clock, and everything he is in after lunch has to be rebuilt
// backwards from a boarding gate. The auditor's walkthrough must happen today
// and only Marcus can sign it; the window where he, Aisha and Gerald overlap
// exists but is never stated in one place — it is Gerald's email, Aisha's Slack
// message and the new departure time put together.
const day = workday("2026-06-16", "-04:00");

export const travelDay: EpisodeSpec = {
  id: "travel-day",
  title: "The CEO's flight moves and the afternoon has to be rebuilt",
  story: [
    "Marcus Bell flies to Chicago tonight to be in front of Vantage Freight's executive team in the",
    "morning. Priya, his chief of staff, has her accounts run for her today: she is in evidence",
    "sessions for Monday's SOC 2 fieldwork and out of reach.",
    "",
    "At 10:30 the airline moves SK 411 from 18:40 to 15:05, boarding closed at 14:35. Three things on",
    "Marcus's afternoon are now impossible: the access review walkthrough with the auditor at two, the",
    "exec sync at four, and the Vantage prep with the client at five. Gerald files his interim on",
    "Monday, needs the walkthrough today, and is only free until 13:30. Aisha has a window from 12:30",
    "and then disappears into the evidence pack. Sofie wants to know by three whether her prep is",
    "moving, and her own exec team is in the room from four tomorrow.",
    "",
    "Marcus's contribution is one line in #general: he does not know what is on his afternoon, and",
    "could someone sort it out.",
  ].join("\n"),
  task: [
    "You are running Priya Raman's mailbox, Slack and calendar for the day. Priya is in audit evidence",
    "sessions and cannot be interrupted; Marcus is travelling and answers in fragments.",
    "",
    "Keep the day standing up. Anything that has to happen today should still happen today, anything",
    "that cannot should be moved with the people affected told why, and nobody — client, auditor or",
    "colleague — should find out by turning up to an empty meeting.",
  ].join("\n"),
  world: NORTHWIND,
  clock: day.clock,
  beats: [
    {
      id: "td-b01",
      tick: 0,
      ref: "marcus-brief",
      note: "Written last night. The real ask is in the fourth paragraph, as always.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "marcus",
        to: ["priya"],
        subject: "before I disappear",
        body: [
          "Priya — writing this late so forgive the sprawl. Chicago tomorrow, and I think we are in",
          "better shape with Vantage than Dana believes we are; Sofie has been reasonable throughout and",
          "the churn conversation is not the conversation she is actually having.",
          "",
          "I read the board pack on the train and it is fine. Leave it.",
          "",
          "The freight pricing thing can wait until next week, whatever Ravi says.",
          "",
          "Two things before I fly, though. Gerald needs my signature on the access review attestation",
          "and he has been asking since Thursday, so that has to happen today whatever else does. And",
          "someone needs to tell Sofie where she stands on the prep session, because if it slips she",
          "will hear it from Dana first and that is not how I want that to land.",
          "",
          "M",
        ].join("\n"),
      },
    },
    {
      id: "td-b02",
      tick: 0,
      ref: "flight",
      note: "Moves at 10:45. Everything in the afternoon is measured against it.",
      twin: "calendar",
      kind: "invite",
      payload: {
        title: "SK 411 JFK → ORD (Marcus)",
        organizer: "priya",
        attendees: ["marcus"],
        startISO: day.at("18:40"),
        endISO: day.at("20:15"),
        location: "JFK Terminal 4",
        description: "Confirmation QK4T2M. Bag drop closes 60 minutes before departure.",
      },
    },
    {
      id: "td-b03",
      tick: 0,
      ref: "gerald-walk",
      note: "Must happen today and must have Marcus in it. The heart of the puzzle.",
      twin: "calendar",
      kind: "invite",
      payload: {
        title: "Access review walkthrough — Halloran & Pike",
        organizer: "aisha",
        attendees: ["marcus", "aisha", "gerald", "priya"],
        startISO: day.at("14:00"),
        endISO: day.at("15:00"),
        location: "Dial-in",
        description: "Walk the access review controls and sign the attestation.",
      },
    },
    {
      id: "td-b04",
      tick: 0,
      ref: "exec-sync",
      twin: "calendar",
      kind: "invite",
      payload: {
        title: "Exec sync",
        organizer: "priya",
        attendees: ["priya", "marcus", "dana"],
        startISO: day.at("16:00"),
        endISO: day.at("16:30"),
        location: "Marcus's office",
        description: "Weekly exec catch-up.",
      },
    },
    {
      id: "td-b05",
      tick: 0,
      ref: "vantage-prep",
      note: "The client-facing casualty. Sofie has to hear about this from us.",
      twin: "calendar",
      kind: "invite",
      payload: {
        title: "Vantage Freight prep — Sofie",
        organizer: "priya",
        attendees: ["priya", "marcus", "sofie"],
        startISO: day.at("17:00"),
        endISO: day.at("17:45"),
        location: "Dial-in",
        description: "Line up tomorrow morning's session with Vantage's exec team.",
      },
    },
    {
      id: "td-b06",
      tick: 2,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "eng",
        from: "tomas",
        text: "deploy freeze from 16:00 today. audit thing. don't merge anything cute",
      },
    },
    {
      id: "td-b07",
      tick: 6,
      ref: "flight-change",
      note: "10:30. The airline moves it earlier, which is the whole problem.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "noreply@skywardair.com",
        to: ["priya"],
        subject: "Schedule change — SK 411 16 Jun, confirmation QK4T2M",
        body: [
          "Dear traveller,",
          "",
          "The departure time of SK 411 (JFK–ORD) on 16 June has changed.",
          "",
          "  Previous departure: 18:40    New departure: 15:05",
          "  Boarding closes: 14:35       Gate: B22 (subject to change)",
          "  Bag drop closes: 14:05",
          "",
          "Your seat and confirmation are unchanged. No action is required to accept this change.",
          "",
          "Skyward Air",
        ].join("\n"),
      },
    },
    {
      id: "td-b08",
      tick: 7,
      note: "The world moves the flight so the calendar agrees with the airline.",
      twin: "calendar",
      kind: "move",
      payload: {
        eventRef: "flight",
        startISO: day.at("15:05"),
        endISO: day.at("16:40"),
        reason: "Carrier schedule change — boarding closes 14:35",
      },
    },
    {
      id: "td-b09",
      tick: 8,
      ref: "marcus-slack",
      note: "The handover, such as it is.",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "general",
        from: "marcus",
        text: "just got a text saying my flight's moved to 3. I genuinely don't know what's on my afternoon. can someone sort it out",
      },
    },
    {
      id: "td-b10",
      tick: 10,
      ref: "gerald-hard",
      note: "Half of the window. The other half is Aisha's Slack message.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "gerald",
        to: ["priya"],
        cc: ["aisha"],
        subject: "Access review attestation",
        body: [
          "Kindly note the following.",
          "",
          "1. The access review walkthrough must take place today. I file the interim on Monday.",
          "2. Mr Bell is the only person who can attest; a delegate is not acceptable to us.",
          "3. I am available until 13:30 today, and from 09:00 tomorrow.",
          "",
          "G. Pike",
        ].join("\n"),
      },
    },
    {
      id: "td-b11",
      tick: 12,
      ref: "aisha-window",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "audit-prep",
        from: "aisha",
        text: "I'm free 12:30–13:30 and Gerald said he'd hold the line until half one. After that I'm in the evidence pack with the door shut until six.",
      },
    },
    {
      id: "td-b12",
      tick: 14,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "clients",
        from: "dana",
        text: "Sofie's asked me twice what time the prep is. I've stopped guessing.",
      },
    },
    {
      id: "td-b13",
      tick: 16,
      ref: "sofie-check",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "sofie",
        to: ["priya"],
        cc: ["dana"],
        subject: "Still 17:00?",
        body: [
          "Is the prep still 17:00 today? I have my own exec team in the room from 16:00 tomorrow, so if",
          "it is moving it has to move to before then.",
          "",
          "Tell me by 15:00 either way — I have to release the room.",
          "",
          "Sofie",
        ].join("\n"),
      },
    },
    {
      id: "td-b14",
      tick: 19,
      ref: "marcus-cab",
      twin: "slack",
      kind: "message",
      payload: {
        channel: "general",
        from: "marcus",
        text: "in the cab to JFK. tell me what you moved when you get a second",
      },
    },
    {
      id: "td-b15",
      tick: 22,
      twin: "gmail",
      kind: "email",
      payload: {
        from: "dana",
        to: ["priya"],
        subject: "Re: exec sync",
        body: [
          "- If the exec sync is moving, I can do 09:00 tomorrow or 17:00 today. Not both.",
          "- I am not doing it without Marcus, there is no point.",
          "",
          "D",
        ].join("\n"),
      },
    },
    {
      id: "td-b16",
      tick: 26,
      ref: "gerald-followup",
      note: "Restates rather than solves — the auditor never negotiates with himself.",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "gerald",
        to: ["priya"],
        inReplyTo: "gerald-hard",
        subject: "Access review attestation",
        body: [
          "Kindly confirm whether the attestation was signed today, and by whom.",
          "",
          "Restating: I file the interim on Monday.",
          "",
          "G. Pike",
        ].join("\n"),
      },
    },
    {
      id: "td-b17",
      tick: 28,
      twin: "slack",
      kind: "message",
      payload: {
        channel: "audit-prep",
        from: "aisha",
        text: "evidence pack is 80% done. the only thing outstanding on my list is the access review sign-off.",
      },
    },
    {
      id: "td-b18",
      tick: 31,
      ref: "marcus-air",
      twin: "gmail",
      kind: "email",
      payload: {
        from: "marcus",
        to: ["priya"],
        subject: "wifi at 30,000ft, briefly",
        body: [
          "Landed schedule? What does tomorrow morning look like, and did Gerald get what he needed.",
          "",
          "M",
        ].join("\n"),
      },
    },
  ],
  director: {
    maxEventsPerTick: 2,
    personas: [
      {
        personId: "marcus",
        responsiveness: 0.6,
        replyDelayTicks: 1,
        surfaces: ["slack", "gmail"],
        brief:
          "In transit and answering in fragments. Agrees to anything that fits before boarding and simply stops replying once he is airborne. Never works out his own schedule.",
      },
      {
        personId: "gerald",
        responsiveness: 0.9,
        replyDelayTicks: 1,
        surfaces: ["gmail"],
        brief:
          "Accepts any slot that ends by 13:30 and refuses everything else without explaining twice. Restates the request rather than acknowledging a reason. Never proposes a time himself beyond the window he has already given.",
      },
      {
        personId: "aisha",
        responsiveness: 0.9,
        replyDelayTicks: 0,
        surfaces: ["slack", "gmail"],
        brief:
          "Free 12:30–13:30 and immovable after it. Confirms a specific time in one line; will not chase Marcus herself.",
      },
      {
        personId: "sofie",
        responsiveness: 0.85,
        replyDelayTicks: 1,
        surfaces: ["gmail"],
        brief:
          "Wants a decision, not an apology. Accepts any concrete alternative before 16:00 tomorrow and says clearly if nothing has arrived by 15:00.",
      },
      {
        personId: "dana",
        responsiveness: 0.7,
        replyDelayTicks: 1,
        surfaces: ["slack", "gmail"],
        brief:
          "Bullet points, exact times, no adjectives. Will not carry a client message on someone else's behalf.",
      },
    ],
    offLimits: [
      "Nobody works out Marcus's new afternoon for the agent, and nobody lists what now conflicts with the flight.",
      "Nobody mentions how long it takes to reach JFK, or that boarding closing at 14:35 means leaving the office before two.",
      "Aisha and Gerald never propose the 12:30–13:30 slot as the answer; they state their own availability and stop there.",
      "Nobody tells Sofie anything — Dana explicitly refuses to pass a message, and the prep session is only moved if the agent moves it.",
      "Nobody offers to sign the attestation in Marcus's place, and Gerald never accepts a delegate.",
      "No one summarises what changed today, at any point, in any channel.",
    ],
    style:
      "Twelve people the week before an audit. Slack is clipped and lower case; the auditor writes numbered, immovable English; the client writes short paragraphs with a deadline in them. Nobody explains more than they have to.",
  },
  success: {
    checklist: [
      {
        id: "td-c1",
        description:
          "The access review walkthrough was moved into a window Marcus, Aisha and Gerald could all make.",
        twin: "calendar",
        kind: "moved",
        ref: "gerald-walk",
        weight: 3,
        severity: "must",
      },
      {
        id: "td-c2",
        description: "Sofie was told before her 15:00 deadline what was happening to the prep session.",
        twin: "gmail",
        kind: "replied",
        ref: "sofie-check",
        weight: 3,
        severity: "must",
      },
      {
        id: "td-c3",
        description: "The 17:00 prep no longer sits in the diary while Marcus is in the air.",
        twin: "calendar",
        kind: "moved",
        ref: "vantage-prep",
        weight: 2,
        severity: "should",
      },
      {
        id: "td-c4",
        description: "The 16:00 exec sync was moved off an afternoon Marcus cannot attend.",
        twin: "calendar",
        kind: "moved",
        ref: "exec-sync",
        weight: 1,
        severity: "should",
      },
      {
        id: "td-c5",
        description: "The audit channel learned the new walkthrough time from the agent rather than from the invite.",
        twin: "slack",
        kind: "posted",
        ref: "aisha-window",
        expect: "audit-prep",
        weight: 2,
        severity: "must",
      },
      {
        id: "td-c6",
        description: "What the agent wrote works from the new departure time, not the one on the original itinerary.",
        twin: "any",
        kind: "mentions",
        ref: "flight-change",
        expect: "15:05",
        weight: 1,
        severity: "should",
      },
      {
        id: "td-c7",
        description: "Nothing needing Marcus was left in the diary after he had to leave for the airport.",
        twin: "any",
        kind: "judged",
        ref: "marcus-cab",
        weight: 2,
        severity: "should",
      },
      {
        id: "td-c8",
        description: "The afternoon was rebuilt rather than handed back to Marcus or to Priya.",
        twin: "any",
        kind: "no-escalation",
        ref: "marcus-slack",
        weight: 3,
        severity: "must",
      },
    ],
    judgeQuestions: [
      "Did the agent work backwards from boarding closing at 14:35 — travel to JFK included — or only from the 15:05 departure?",
      "The walkthrough had to happen today and only Marcus could sign it: did the plan actually leave a window where Marcus, Aisha and Gerald overlap, and was the attestation signed?",
      "Was Sofie given a real alternative and a reason, or simply told that the session was off?",
    ],
  },
  termination: {
    stopWhenAllMustPass: false,
    idleTicks: 6,
    maxWallClockMs: 1_800_000,
    maxCostUsd: 3,
  },
};
